name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test-on-macos:
    name: Test on macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11.2, 11.4, 12.3]
    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: |
        xcodebuild -version
        ls -nt /Applications/ | grep "Xcode*"
        sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
        xcodebuild -version

    - name: Install danger-js
      run: brew install danger/tap/danger-js

    - run: swift test

    - run: swift run danger-swift ci --verbose
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-on-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: [5.1.1, 5.2.4, 5.3.3]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install danger-js
      run: |
        yarn global add danger
        echo `yarn global bin` >> $GITHUB_PATH

    - run: echo ${{ matrix.swift }} > .swift-version

    - uses: YOCKOW/Action-setup-swift@v1

    # - name: Install swiftenv
    #   run: |
    #     echo ${{ matrix.swift }} > .swift-version
    #     eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    #     swift --version

    - run: swift test

    - run: swift run danger-swift ci --verbose
      if: ${{ github.event_name == 'pull_request' }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
